### ISSUE TITLE
Add https://tulu.la to a list of conferences/cfp

### ISSUE THREAD

**Issue by m0sth8** [coryhouse/speaker-starter-kit#10]
Hi! 

Thank you for the speaker starter kit, it is awesome. I found so many useful resources.

We're building an event aggregator with the most accurate information about Tech events. A lot of open CFPs https://tulu.la/call-for-papers/ . A calendar for events https://tulu.la/events/?view=calendar . Forum for first time speakers and more. I would be happy to see it in this list.

Best,
Slava

**Comment by coryhouse** [comment]
Hi Slava - Thanks! I'd accept a PR to add it. :)

**Comment by m0sth8** [comment]
Thank you. Added PR!
